openapi: 3.0.1
info:
  title: CarAPI
  description: ''
  version: '1.0'
servers:
  - url: https://apimanagement-demo-service.azure-api.net/vehicles
paths:
  /getallmanufacturers:
    get:
      summary: getallmanufacturers
      description: getallmanufacturers
      operationId: getallmanufacturers
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]